apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: jaipal-dev-ns
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jaipal-app
  name: jaipal-app
  namespace: jaipal-dev-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jaipal-app
  strategy: {}
  template: # tempalte of pods 
    metadata:
      creationTimestamp: null
      labels:
        app: jaipal-app # label of pods 
    spec:
      containers:
      - image: dockerashu/ashumobiwebapp:6
        name: jaipalmobiwebapp
        ports:
        - containerPort: 80
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jaipalsvc1
  name: jaipalsvc1
  namespace: jaipal-dev-ns
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector: # is finding pod using pod labels to create Endpoints 
    app: jaipal-app # exact label of pods 
  type: NodePort
status:
  loadBalancer: {}
  
  
